// <auto-generated />
using InvestorsAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestorsAPI.Migrations
{
    [DbContext(typeof(InvestorDbContext))]
    [Migration("20250117225432_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvestorsAPI.Entities.Fund", b =>
                {
                    b.Property<int>("FundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FundId"));

                    b.Property<string>("FundName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FundId");

                    b.ToTable("Funds");
                });

            modelBuilder.Entity("InvestorsAPI.Entities.Investor", b =>
                {
                    b.Property<int>("InvestorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestorId"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InvestorId");

                    b.ToTable("Investors");
                });

            modelBuilder.Entity("InvestorsAPI.Entities.InvestorFund", b =>
                {
                    b.Property<int>("InvestorId")
                        .HasColumnType("int");

                    b.Property<int>("FundId")
                        .HasColumnType("int");

                    b.HasKey("InvestorId", "FundId");

                    b.HasIndex("FundId");

                    b.ToTable("InvestorFunds");
                });

            modelBuilder.Entity("InvestorsAPI.Entities.InvestorFund", b =>
                {
                    b.HasOne("InvestorsAPI.Entities.Fund", "Fund")
                        .WithMany("InvestorFunds")
                        .HasForeignKey("FundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvestorsAPI.Entities.Investor", "Investor")
                        .WithMany("InvestorFunds")
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("InvestorsAPI.Entities.Fund", b =>
                {
                    b.Navigation("InvestorFunds");
                });

            modelBuilder.Entity("InvestorsAPI.Entities.Investor", b =>
                {
                    b.Navigation("InvestorFunds");
                });
#pragma warning restore 612, 618
        }
    }
}
